/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package MyApp;
import MyLib.Client;
import MyLib.Agent;
import MyLib.Admin;
import MyLib.SystemUser;
import MyLib.Reserve;
import java.util.ArrayList;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pcmya
 */
public class Login extends javax.swing.JFrame {
    
    public static ArrayList<Client> clients = new ArrayList<>();
    public static ArrayList<Agent> agents = new ArrayList<>();

    public static ArrayList<Admin> admins = new ArrayList<>();

    public static ArrayList<Reserve> history = new ArrayList<>();
    
    private Client loggedIn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    public Login() {
        initComponents();
        
        ImageIcon raw = new ImageIcon(getClass().getResource("/MyApp/images/lancaster logo.png"));
        Image scaled = raw.getImage().getScaledInstance(350, 200, Image.SCALE_SMOOTH);
        logoimage.setIcon(new ImageIcon(scaled));
        logoimage.setText("");
    }
    
    static {
    clients.add(new Client("User","sampleuser@gmail.com","sample_user","password1","0916123456"));
    agents.add(new Agent(101010, "Agent", "password2"));
    admins.add(new Admin(202020, "Admin", "password3"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        userType = new javax.swing.JComboBox<>();
        login = new javax.swing.JButton();
        toRegister = new javax.swing.JButton();
        sideImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1083, 759));
        setResizable(false);

        logoimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/images/lancaster logo.png"))); // NOI18N
        logoimage.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Log In");
        jLabel1.setToolTipText("");

        usernameField.setText("Username");
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        passwordField.setText("Password");
        passwordField.addActionListener(this::passwordFieldActionPerformed);

        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Agent", "Admin" }));
        userType.addActionListener(this::userTypeActionPerformed);

        login.setText("Log in");
        login.addActionListener(this::loginActionPerformed);

        toRegister.setText("Don't have an account yet? Register here!");
        toRegister.addActionListener(this::toRegisterActionPerformed);

        sideImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/images/home_image_1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sideImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoimage, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toRegister)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                            .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logoimage, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(toRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideImg, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 900, 747);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    String role     = (String) userType.getSelectedItem();
    String username = usernameField.getText();
    String password = new String(passwordField.getPassword());
    
    if (role.equals("Client")) {
        
        for (Client c : clients) {
            if (c.login(username, password)) {
                JOptionPane.showMessageDialog(this, "Welcome, " + c.getName() + "!");
                new ClientDashboard(c).setVisible(true);
                this.dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Invalid username or password!");
    } else if (role.equals("Agent")) {
    try {
        int agentID = Integer.parseInt(usernameField.getText());
       
        for (Agent a : agents) {
            if (a.login(agentID, password)) {
                JOptionPane.showMessageDialog(this, "Welcome, " + a.getName() + "!");
                new AgentDashboard(a).setVisible(true);
                this.dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Invalid ID or password!");
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Agent ID must be a number!");
    } //catch
    }  else if (role.equals("Admin")) {
        try {
            int adminID = Integer.parseInt(username); // ← parse it first!
            for (Admin ad : admins) {
                if (ad.login(adminID, password)) {
                    JOptionPane.showMessageDialog(this, "Welcome, " + ad.getName() + "!");
                    new AdminDashboard(ad).setVisible(true);
                    this.dispose();
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Invalid ID or password!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Admin ID must be a number!");
        }
    }
    }//GEN-LAST:event_loginActionPerformed

    private void toRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRegisterActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toRegisterActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        String selected = (String) userType.getSelectedItem();
    
        if (selected.equals("Client")) {
            usernameField.setText("Username");
            toRegister.setVisible(true);
        } else if (selected.equals("Agent")) {
            usernameField.setText("Agent ID");
            toRegister.setVisible(false);
        } else if (selected.equals("Admin")) {
            usernameField.setText("Admin ID");
            toRegister.setVisible(false);
        }
    }//GEN-LAST:event_userTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel logoimage;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel sideImg;
    private javax.swing.JButton toRegister;
    private javax.swing.JComboBox<String> userType;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
