/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
import MyLib.Client;
import MyLib.EstateProperties;
import MyLib.Property;
import MyLib.Reserve;
import MyLib.Transaction;
import MyApp.Login;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.awt.FlowLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
/**
 *
 * @author emarie
 */
public class MyTransaction extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyTransaction.class.getName());

    private Client loggedIn;
    private Property chosenBlkLot;
    /**
     * Creates new form MyTransaction
     */
    public MyTransaction() {
        initComponents();
        transacPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 20, 20));
        displayPastTransactions(MyApp.Login.history);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transacPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 787));
        setResizable(false);
        setSize(new java.awt.Dimension(1025, 787));

        jLabel1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N
        jLabel1.setText("My Transactions");

        jLabel2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        jLabel2.setText("View past transactions and receipt.");

        jScrollPane1.setViewportView(transacPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void displayPastTransactions(ArrayList<MyLib.Reserve> history) {
        transacPanel.removeAll();

        if (history == null || history.isEmpty()) {
            // Display empty state message
            JLabel emptyMsg = new JLabel("You haven't made any transactions yet.");
            emptyMsg.setFont(new java.awt.Font("Segoe UI", 0, 18));
            emptyMsg.setForeground(Color.GRAY);
            transacPanel.add(emptyMsg);
        } 
        else {
            for (MyLib.Reserve record : history) {
                JPanel card = new JPanel();
                
                card.setPreferredSize(new Dimension(600, 500));
                card.setBackground(Color.WHITE);
                card.setBorder(BorderFactory.createLineBorder(new Color(230, 230, 230)));
                card.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

                String status = record.getProperty().getStatus();
                String type = status.equalsIgnoreCase("Sold") ? "PURCHASE" : "RESERVATION";
                
                String propertyInfo = "Property: Block " + record.getProperty().getBlockLoc() + " Lot " + record.getProperty().getLotLoc();
                
                card.add(new JLabel("  Type: " + type));
                card.add(new JLabel(propertyInfo));
                card.add(new JLabel("  Status: " + status));
                
                transacPanel.add(card);
                
            }
            int height = history.size()*300;
            transacPanel.setPreferredSize(new Dimension(384, height));
        }

        transacPanel.revalidate();
        transacPanel.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyTransaction().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel transacPanel;
    // End of variables declaration//GEN-END:variables
}
