/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

import MyLib.EstateProperties;
import MyLib.Property;
import MyLib.Client;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian Aranza
 */
public class PropertiesWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PropertiesWindow.class.getName());
    
    private Client loggedIn;
    
    /**
     * Creates new form Properties
     */
    EstateProperties ep;

    public PropertiesWindow(Client client) {  
        initComponents();
        ep = new EstateProperties();
        loadProperties();

        this.loggedIn = client;  
        greetingLabel.setText("Welcome, " + loggedIn.getName() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSearch = new java.awt.Button();
        inputSize = new javax.swing.JTextField();
        inputBlock = new javax.swing.JTextField();
        inputPrice = new javax.swing.JTextField();
        cmbModel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReset = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        btnProceedTransact = new java.awt.Button();
        chosenBlockInput = new javax.swing.JTextField();
        chosenLotInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        greetingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Block", "Lot", "Size (sqm)", "Price", "Model", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSearch.setLabel("Search Property");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        inputSize.addActionListener(this::inputSizeActionPerformed);

        inputBlock.addActionListener(this::inputBlockActionPerformed);

        cmbModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Anica", "Alice", "Thea", "Adelle" }));

        jLabel1.setText("Enter Size:");

        jLabel2.setText("Enter Block:");

        jLabel3.setText("Enter Your Budget:");

        jLabel4.setText("Select Mode:");

        btnReset.setLabel("Reset Search");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("Dashboard");

        btnProceedTransact.setLabel("PROCEED TRANSACTION");
        btnProceedTransact.addActionListener(this::btnProceedTransactActionPerformed);

        chosenBlockInput.addActionListener(this::chosenBlockInputActionPerformed);

        chosenLotInput.addActionListener(this::chosenLotInputActionPerformed);

        jLabel6.setText("Enter Desired Block:");

        jLabel7.setText("Enter Desired Lot:");

        greetingLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        greetingLabel.setText("Welcome, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSize, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chosenBlockInput))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(chosenLotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnProceedTransact, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greetingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chosenBlockInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chosenLotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(btnProceedTransact, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        Integer blockLoc = null;
        Double price = null;
        Double size = null;
        String model = null;

        String blockText = inputBlock.getText().trim();
        if (!blockText.isEmpty()) {
            try {
                blockLoc = Integer.parseInt(blockText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Block Number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String priceText = inputPrice.getText().trim();
        if (!priceText.isEmpty()) {
            try {
                price = Double.parseDouble(priceText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Price Format", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String sizeText = inputSize.getText().trim();
        if (!sizeText.isEmpty()) {
            try {
                size = Double.parseDouble(sizeText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Size Format", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String selectedModel = cmbModel.getSelectedItem().toString();
        if (!selectedModel.equals("-")) {
            model = selectedModel;
        }

        ArrayList<Property> results = ep.searchProperties(blockLoc, price, size, model);

        updateTable(results);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        if (evt.getSource() == btnReset) {
            inputBlock.setText("");
            inputPrice.setText("");
            inputSize.setText("");
            
            cmbModel.setSelectedIndex(0);
            
            loadProperties();
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnProceedTransactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedTransactActionPerformed
        // TODO add your handling code here:
        Integer blockNum = null;
        Integer lotNum = null;
        
        String chosenBlockText = chosenBlockInput.getText().trim();
        String chosenLotText = chosenLotInput.getText().trim();
        
        if (!chosenBlockText.isEmpty()) {
            try {
                blockNum = Integer.parseInt(chosenBlockText);
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Block Number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter a Block Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!chosenLotText.isEmpty()) {
            try {
                lotNum = Integer.parseInt(chosenLotText);
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Lot Number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter a Lot Number", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        Transaction transactWindow = new Transaction(blockNum, lotNum);
        transactWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProceedTransactActionPerformed

    private void chosenBlockInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosenBlockInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chosenBlockInputActionPerformed

    private void chosenLotInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosenLotInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chosenLotInputActionPerformed

    private void inputBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBlockActionPerformed

    private void inputSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSizeActionPerformed

    private void loadProperties() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Property p : ep.getProperties()) {
            Object[] row = {
                p.getBlockLoc(),
                p.getLotLoc(),
                p.getSize(),
                String.format("₱ %.2f", p.getPrice()),
                p.getModel().displayModelDetails(),
                p.getStatus()
            };
            model.addRow(row);
            
            updateTable(ep.getProperties());
        }
    }
    
    private void updateTable(ArrayList<Property> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Property p : list) {
            Object[] row = {
                p.getBlockLoc(),
                p.getLotLoc(),
                p.getSize(),
                String.format("₱ %.2f", p.getPrice()),
                p.getModel().displayModelDetails(),
                p.getStatus()
            };
            model.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new PropertiesWindow().setVisible(true));*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnProceedTransact;
    private java.awt.Button btnReset;
    private java.awt.Button btnSearch;
    private javax.swing.JTextField chosenBlockInput;
    private javax.swing.JTextField chosenLotInput;
    private javax.swing.JComboBox<String> cmbModel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JTextField inputBlock;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JTextField inputSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
